"""Ed25519 public key for package signature verification.

Generated by: python scripts/signing/generate_keys.py
DO NOT EDIT -- regenerate keys if compromised.
"""

PUBLIC_KEY_PEM = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAD024AQBtqJY8RlF1Ie0VQyuCY36OTgsXi991uPUJbo8=
-----END PUBLIC KEY-----
""".strip()
