"""One-time Ed25519 keypair generation for package signing.

Usage:
    python scripts/signing/generate_keys.py

Generates:
    scripts/signing/private.key  — NEVER commit, NEVER distribute
    backend/src/q2h/upgrade/public_key.py — embedded in app for verification
"""

import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization
from pathlib import Path


def generate_keypair():
    keys_dir = Path(__file__).parent
    private_path = keys_dir / "private.key"
    if private_path.exists():
        print("ERROR: private.key already exists. Delete it first to regenerate.")
        print("WARNING: Regenerating invalidates ALL previously signed packages!")
        sys.exit(1)

    private_key = Ed25519PrivateKey.generate()

    # Private key (PEM, unencrypted)
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    # Public key (PEM)
    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    # Save private key
    keys_dir.mkdir(parents=True, exist_ok=True)
    private_path.write_bytes(private_pem)

    # Write public key as Python module
    public_key_content = (
        '"""Ed25519 public key for package signature verification.\n'
        "\n"
        "Generated by: python scripts/signing/generate_keys.py\n"
        'DO NOT EDIT -- regenerate keys if compromised.\n"""\n'
        "\n"
        f'PUBLIC_KEY_PEM = """\n{public_pem.decode()}""".strip()\n'
    )

    root = keys_dir.parent.parent
    public_key_path = root / "backend" / "src" / "q2h" / "upgrade" / "public_key.py"
    public_key_path.parent.mkdir(parents=True, exist_ok=True)
    public_key_path.write_text(public_key_content, encoding="utf-8")

    print(f"Private key: {private_path}")
    print(f"Public key:  {public_key_path}")
    print()
    print("IMPORTANT: Never commit private.key to git!")
    print("IMPORTANT: Keep private.key secure — it's the only way to sign packages.")


if __name__ == "__main__":
    generate_keypair()
